#!/usr/bin/env bash
# Best-effort autodetection of project shape. Prints a draft .nahj/profile.yaml
# to stdout. The orchestrator presents this to the user for confirmation on first
# run, then saves it.
#
# Usage:
#   bash detect-profile.sh > .nahj/profile.yaml
#
# Detection is opportunistic — fields it can't infer are emitted as TODO so the
# user can fill them in. Never silently guesses commands.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

project_name="$(basename "$repo_root")"

# Default branch: prefer remote HEAD, fall back to common names.
default_branch="$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's|^origin/||' || true)"
if [[ -z "$default_branch" ]]; then
  for candidate in develop main master; do
    if git rev-parse --verify "$candidate" >/dev/null 2>&1; then
      default_branch="$candidate"
      break
    fi
  done
fi
default_branch="${default_branch:-main}"

# Worktrees dir: convention is sibling-to-repo.
worktrees_dir="../${project_name}-worktrees"

# Test commands: try root-level patterns first (most projects), then common
# monorepo subdirs (apps/, packages/, services/) as fallbacks.
declare -a test_cmds=()
[[ -f pytest.ini || -f pyproject.toml ]] && test_cmds+=("pytest")
[[ -f package.json ]] && grep -q '"test"' package.json 2>/dev/null && test_cmds+=("npm run test")
[[ -f Cargo.toml ]] && test_cmds+=("cargo test")
[[ -f go.mod ]] && test_cmds+=("go test ./...")
# Monorepo fallbacks — only added if root patterns came up empty.
if [[ ${#test_cmds[@]} -eq 0 ]]; then
  for sub in apps/backend packages/backend services/backend backend; do
    [[ -f "$sub/pytest.ini" || -f "$sub/pyproject.toml" ]] && test_cmds+=("cd $sub && pytest") && break
  done
  for sub in apps/frontend packages/frontend services/frontend frontend web; do
    [[ -f "$sub/package.json" ]] && grep -q '"test"' "$sub/package.json" 2>/dev/null && test_cmds+=("cd $sub && npm run test") && break
  done
fi

# Migrate command + path glob (for the merger to skip the migrate step when a
# branch didn't touch schema). Only emit if we see a known migration tool.
migrate_cmd=""
migrate_path_glob=""
if [[ -f alembic.ini ]]; then
  migrate_cmd="alembic upgrade head"
  migrate_path_glob="alembic/versions"
elif [[ -d prisma && -f prisma/schema.prisma ]]; then
  migrate_cmd="npx prisma migrate deploy"
  migrate_path_glob="prisma/migrations"
elif [[ -d db/migrate ]]; then
  migrate_cmd="bin/rails db:migrate"
  migrate_path_glob="db/migrate"
else
  for sub in apps/backend packages/backend services/backend backend; do
    if [[ -f "$sub/alembic.ini" ]]; then
      migrate_cmd="cd $sub && alembic upgrade head"
      migrate_path_glob="$sub/alembic/versions"
      break
    fi
  done
fi

emit_yaml_list() {
  local -n arr=$1
  if [[ ${#arr[@]} -eq 0 ]]; then
    echo "  [] # TODO: add the project's test command(s)"
  else
    for cmd in "${arr[@]}"; do
      printf '  - %s\n' "$cmd"
    done
  fi
}

cat <<EOF
# Generated by nahj detect-profile.sh on $(date -Iseconds)
# Review and edit before saving — fields marked TODO need your input.
schema_version: 1
project_name: $project_name
default_branch: $default_branch
worktrees_dir: $worktrees_dir
default_label: nahj

test_cmds:
$(emit_yaml_list test_cmds)

EOF

if [[ -n "$migrate_cmd" ]]; then
  printf 'migrate_cmd: %s\n' "$migrate_cmd"
  printf 'migrate_path_glob: %s\n\n' "$migrate_path_glob"
else
  printf '# migrate_cmd: ""        # TODO: set if your project has migrations\n'
  printf '# migrate_path_glob: ""  # TODO: extended-regex matching migration-file paths (e.g. "alembic/versions|prisma/migrations")\n\n'
fi

cat <<'EOF'
# Per-issue isolation. Leave both blank if your project needs no scratch
# environment (frontend-only, libraries, CLIs, etc.). The implementer reads
# ${N} as its issue number; the cleanup phase invokes the recorded teardown
# without needing to know the project's stack.
isolation:
  scratch_setup: |
    # TODO: shell commands to set up an isolated env for issue ${N}.
    # Example (Postgres in docker):
    #   docker exec myproj-db createdb -U postgres "nahj_test_issue_${N}"
    #   export DATABASE_URL="postgresql://postgres@127.0.0.1:5432/nahj_test_issue_${N}"
  scratch_teardown: |
    # TODO: matching teardown commands.
    # Example (Postgres in docker):
    #   docker exec myproj-db dropdb -U postgres "nahj_test_issue_${N}" 2>/dev/null || true

# Save this file to .nahj/profile.yaml. Commit it (recommended — your team shares
# the setup) or add /.nahj/ to .gitignore (per-developer config).
EOF
